### ISSUE TITLE
Identifying  `json:"-"` 

### ISSUE THREAD

**Issue by dsbhayze** [go-swagno/swagno#14]
First of all, great project, buddy.
But could you take a look on the process of `json:"-"` in the struct?
e.g.:
type PersonResponse struct {
	ID   int          `json:"-"`
	Name string `json:"name"`
	Age  int        `json:"age"`
}
On this context, I don't want to return the id to the client app.
An easy way to do that, it's simple adding the annotation `json:"-"`
But it seems swagno has some problem reading that.
It actually create this payload:
{
      "-": 1
      "name": "Nick",
      "age": 38
}

**Comment by anilsenay** [comment]
Fixed in release v1.0.0
