### ISSUE TITLE
Detect Recursive structs

### ISSUE THREAD

**Issue by ocomsoft** [go-swagno/swagno#15]
I cannot share my structs but somehow I have structs that relate to structs that relate back to structs so the `body` or `ret` param for the EndPoint function is recursive. 

The code just freezes on:
```
sw.GenerateDocs()
```

I think it's a Struct similar to this:

```
type InParam struct {
 Other *InParam
}
````

I hope this helps. I love the idea of this project

**Comment by anilsenay** [comment]
Fixed in release v1.0.0
