### ISSUE TITLE
Singleton in the handler prevent to launch multiple webserver with each their own SwaggerUI in the same Golang thread

### ISSUE THREAD

**Issue by itdove** [go-swagno/swagno#31]
In the where you want to run multiple http server with each of them having their own swagerUI in the same golang thread only the first one is active.

For example, I have 3 http service running in my main thread and each on different ports.
For each of these servers, I create a *swagno.Swagger and add to this a number of endpoints, then I add a route to the swagger like this:

```
...
	sw := swagno.New(swagno.Config{Title: "service API", Version: "v1.0.0", Host: u.Host})
        router.PathPrefix("/swagger").Handler(swagger.SwaggerHandler(sw.MustToJson()))

	go func() {
		// Launch server
		logger.Info().Msgf("launch webserver %s", ctx.Value(types.ServiceNameKey))
		if err := srv.ListenAndServe(); err != http.ErrServerClosed {
			// unexpected error. port in use?
			logger.Fatal().Msgf("ListenAndServe(): %v", err)
		}
	}()
...
```

because [this](https://github.com/go-swagno/swagno-http/blob/master/swagger/handler.go#L17) handler is a singleton, the same handler is used for all http.servers.

I workaround that by writing my own handler for the "/swagger" path prefix:

```
		router.PathPrefix("/swagger").HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			prefix := "/swagger"
			handler := swaggerUi.Handler
			handler.Prefix = prefix
			switch r.RequestURI {
			case prefix, prefix + "/":
				http.Redirect(w, r, prefix+"/index.html", http.StatusMovedPermanently)
			case prefix + "/doc.json":
				fmt.Fprint(w, string(sw.MustToJson()))
			default:
				handler.ServeHTTP(w, r)
			}
		})
```

A possbile change and keep the backward compatibility, just to not have the swaggerDoc var as a singleton anymore.

```
	if swaggerDoc == "" {
		swaggerDoc = string(doc)
	}
....
```
become

```
...
		swaggerDoc := string(doc)
...
```

**Comment by anilsenay** [comment]
Hi @itdove, thank you for mentioning this issue. I have just opened a PR for fix: https://github.com/go-swagno/swagno-http/pull/1

**Comment by anilsenay** [comment]
I just released new [`swagno-http`](https://github.com/go-swagno/swagno-http) package. Can you update your package and tell me if there is any issue?
