### ISSUE TITLE
Add a method to enable authentication using Bearer token

### ISSUE THREAD

**Issue by itdove** [go-swagno/swagno#32]
Hi,

If we want to use Bearer token authentication with with swagger we need to be able to create a security definition as follow:

```
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT  
```
as explained here https://swagger.io/docs/specification/authentication/bearer-authentication

I can see that the doc.json generated when we use swagno contains a securityDefinitions key but no securitySchemes.

so wonder if creating a `SetBearerTokenAuth` here https://github.com/go-swagno/swagno/blob/master/auth.go in order to have this generated?

Maybe there is another way to be able to setup the swagger with that scheme but I didn't find it.

Would be interesting also to have a kind of SetCustomAuth() method allowing to setup a auth configuration even if the method is not available.

thx.

**Comment by anilsenay** [comment]
Hi @itdove,

First of all, the documentation you mention is for swagger v3 but in this project, we use swagger v2. So you should check this page: https://swagger.io/docs/specification/2-0/authentication/

If [Api Keys](https://swagger.io/docs/specification/2-0/authentication/api-keys/) may help you, can you try [SetApiKeyAuth](https://github.com/go-swagno/swagno/blob/434385abf37109a10b0cb9f38c7dd02daa3c7106/auth.go#L20) function?

It mentioned here in our documentation: https://github.com/go-swagno/swagno?tab=readme-ov-file#security-optional

**Comment by itdove** [comment]
Hi @anilsenay 

Do you mean I can use the SetApiKeyAuth to populate the Bearer token with my token?
What should be the "in" parameter in that case?

**Comment by anilsenay** [comment]
in parameter means where to put api key, in your case it will be `header` i assume. And `name` parameter will be header key which is `Authorization` I guess.

**Comment by itdove** [comment]
Now I have this in my doc.json
```
  "schemes": [
    "https",
    "http"
  ],
  "securityDefinitions": {
    "Authorization": {
      "type": "apiKey",
      "description": "JWT Token",
      "name": "Authorization",
      "in": "header"
    }
  }
  ```
  but when I call an API, the header is not showing.
  Is there something else to do ?

**Comment by anilsenay** [comment]
in Swagger UI, there is button:
![resim](https://github.com/user-attachments/assets/a0f106db-dd47-4ea5-a518-09d048c5e951)

click it and enter your token:
![resim](https://github.com/user-attachments/assets/e9969187-0358-4240-b56e-dd5b954bca9d)

then all requests will be sent with this token in request header.

**Comment by itdove** [comment]
yes I have that but it seems the header is not added to the request.

**Comment by anilsenay** [comment]
Ah, I see. In endpoint level you should add [WithSecurity](https://github.com/go-swagno/swagno/blob/master/components/endpoint/endpoints.go#L219) option to endpoints you want to add. I think it will be something like this:

```go
security := []map[string][]string{map[string][]string{"Authorization": []string{}}}
```

```go
WithSecurity(security)
```

I know its kind a ugly, maybe we could make it simple parameter in next release

---

in your doc.json, it should be something like this example (`Authorization` instead of `APIKeyQueryParam`):

![resim](https://github.com/user-attachments/assets/63bfc9c8-c1bd-4188-8d91-8e06cb21fa0c)

**Comment by itdove** [comment]
yes I have the endpoint
```
        "security": [
          {
            "Authorization": []
          }
        ]

```
and for the whole doc:
```
  "securityDefinitions": {
    "Authorization": {
      "type": "apiKey",
      "description": "JWT Token",
      "name": "Authorization",
      "in": "header"
    }
    ```
    
    but still the header is not passed to the request.

**Comment by itdove** [comment]
Wonder if there is not a bug here as in the doc, the securityDefinitions["APIKeyHeader].name = "X-API-Key".
but in my doc.json I have securityDefinitions["Authorization"].name = "Authorization", the swagno set the name and the map key to the same value.

**Comment by anilsenay** [comment]
Hmm, I think your json looks like fine, honestly I have no idea. 

Its similar in this example: https://petstore.swagger.io/ (https://petstore.swagger.io/v2/swagger.json)

**Comment by anilsenay** [comment]
> Wonder if there is not a bug here as in the doc, the securityDefinitions["APIKeyHeader].name = "X-API-Key". but in my doc.json I have securityDefinitions["Authorization"].name = "Authorization", the swagno set the name and the map key to the same value.

I think it should not be a problem becuase in [example](https://petstore.swagger.io/v2/swagger.json) its similar:

![resim](https://github.com/user-attachments/assets/87b051cb-966f-457e-9fe3-e328727cafd4)
![resim](https://github.com/user-attachments/assets/fddb56ab-ed5b-444c-a814-f0d75711c708)

**Comment by itdove** [comment]
ok, it is working now, maybe a browser cache issue.
Thank you very much.

**Comment by anilsenay** [comment]
> ok, it is working now, maybe a browser cache issue. Thank you very much.

nicee! You're welcome 🙌
