### ISSUE TITLE
Why does WithParams replace an array of params instead of concatenating with it?

### ISSUE THREAD

**Issue by bestietamer** [go-swagno/swagno#40]
In my use case, I need to invoke `WithParams` multiple times, but I observed that the last call to `WithParams` overwrites the results of the previous ones. Upon further investigation, I noticed the following implementation in `endpoints.go`:
<pre>
func WithParams(params ...*parameter.Parameter) EndPointOption {
	return func(e *EndPoint) {
		e.params = params
	}
}
</pre>

Could you clarify why the params array is replaced instead of being appended? This approach appears to limit functionality.

**Comment by anilsenay** [comment]
`WithParams` accepts multiple parameters(`...*parameter.Parameter`) already, why do you need it twice? I wonder your case, can you share your use case for me to understand?

**Comment by bestietamer** [comment]
Sure @anilsenay , here is my code:

<pre>
group.GET(
		":telegram_id/subscribers",
		c.swagger.Get(base, "{telegram_id}/subscribers", "Get subscribers").
			Int64Param("telegram_id").
			Pagination().
			Handle(c.getSubscribers, ApiPlayersResponseDTO{})...)
</pre>

Here `c` is my `Controller`, and `c.swagger` is a `SwaggerHelper` struct, which has a `Get` method to create a GET endpoint. It returns a `SwaggerEndpoint` pointer, a struct with chain methods like `IntParam`, `StrParam`, `Pagination`, and others, which internally add Gin endpoints to parse parameters accordingly, and also add options to the `[]endpoint.EndPointOption` array. After calling all the necessary functions, I finish with `Handle(gin.Handler, body: interface{})`, which returns the array of previously added Gin middlewares.

I designed this to avoid writing code twice: first for Gin handlers, and then for Swagger documentation. Later, I can simply call `c.swagger.Endpoints()`, which forms a `[]*endpoint.EndPoint` array for the `AddEndpoints` method. However, this approach breaks here:

<pre>
func (se *SwaggerEndpoint) IntParam(name string) *SwaggerEndpoint {
	se.options = append(
		se.options,
		endpoint.WithParams(parameter.IntParam(name, parameter.Path, parameter.WithRequired())),
	)
	se.ginHandlers = append(se.ginHandlers, utils.WithIntParam(name))
	return se
}
</pre>

As you can see, I append new parameters to the existing ones, but due to the fact that `WithParams` in Swagno replaces the parameters instead of concatenating them, only the last added options will work.

**Comment by anilsenay** [comment]
@bestietamer, got your point, actually I was planning to do similar for my projects. 

I guess changing it as append instead of replace works and won't break anything but I want to think about another cases before changing the current behavior. I am gonna check it tomorrow.

Thank you for sharing your use case 🙏

**Comment by anilsenay** [comment]
Hi @bestietamer,

I think `e.params = params` is more appropriate than `e.params = append(e.params, params)`.
In my opinion, WithXxx() functions should work this way.

However, considering your use case, I believe making this change wouldn't harm anyone and could improve the user experience in your case.

I will do this change and create a new release soon. Maybe I will come up with better solution until then.

**Comment by anilsenay** [comment]
https://github.com/go-swagno/swagno/releases/tag/v1.2.3

`go get github.com/go-swagno/swagno@v1.2.3`

I released a new version as pre-release, it should solves your issue.

@bestietamer
